### PR TITLE
Add ability to set default container via dir-locals.

### PR DESCRIPTION
**Pull request by olymk2**
Small change so that each time you load your project you no longer have to select your container, It will use the value you have set in (pythonic-docker-compose-container-name) if that is nil (the default) the current behaviour will be used.

let me know what you think :)

### CODE REVIEW

**Comment by proofit404** [comment]
Looks good so far! Thank you for your contribution!

What's going on with `^L` chars in the diff?

P.S. Check out https://github.com/purcell/page-break-lines package :D

**Comment by olymk2** [comment]
that's a good question emacs showed them I thought I had removed them, I will try that package out :)

OR should they be there for page-break-lines ?

**Comment by olymk2** [comment]
should have followed the link, I guess they are intentional for your own use shall I put them back in ?

**Comment by proofit404** [comment]
Yes, put them back, please :)

**Comment by olymk2** [comment]
done

**Comment by proofit404** [comment]
Great! Thanks!

**Pull request merged**
